export const FETCH_RATES = 'FETCH_RATES';
export const FETCH_RATES_ERROR = 'FETCH_RATES_ERROR';
export const LOADING_TRUE = 'LOADING_TRUE';
export const LOADING_FALSE = 'LOADING_FALSE';
export const SET_BASE_VALUE = 'SET_BASE_VALUE';
export const SET_SYMBOLS_VALUE = 'SET_SYMBOLS_VALUE';
export const FETCH_CONVERT_RATES = 'FETCH_CONVERT_RATES';
export const FETCH_CONVERT_RATES_ERROR = 'FETCH_CONVERT_RATES_ERROR';
